
CREATE TABLE home_data (
    street_address INT NOT NULL PRIMARY KEY,
    zip INT NOT NULL,
    city VARCHAR(255),
    state VARCHAR(255),
    price DECIMAL(10 , 2 ),
    home_type VARCHAR(255),
    bedrooms INT,
    bathrooms INT,
    finished_sq_footage INT,
    lot_size_sq_footage INT,
    year_built INT,
    year_updated INT,
    number_of_floors INT,
    parking_type VARCHAR(255),
    heating_sources VARCHAR(255),
    heating_system VARCHAR(255),
    floor_covering VARCHAR(255),
    number_of_rooms INT,
    neighborhood VARCHAR(255),
    shool_district VARCHAR(255),
    sold_binary INT NOT NULL CHECK (sold_binary > - 1 AND sold_binary < 2),
    last_sold_date VARCHAR(255),
    last_sale_price DECIMAL(10 , 2 ),
    appliances VARCHAR(500),
    roof_type VARCHAR(255),
    room_types VARCHAR(500)
)
